### ISSUE TITLE
drupal console fails if drupal/web has an empty composer.json file

### ISSUE THREAD

**Issue by badrange** [webflo/drupal-finder#12]
I was advised in https://github.com/hechoendrupal/drupal-console/issues/2770#issuecomment-276711467 to file this issue here, since drupal console uses this project. 

The issue can be seen clearly here: 

Normal situation: 

```
[vagrant@local web]$ /vagrant/drupal/current/vendor/drupal/console/bin/drupal site:statistics
 -------------------------- ----------
  Name                       Quantity
 -------------------------- ----------
  Node:"Article"             3
  Node:"Event"               2
  Node:"Place"               2167
```

But what if you by mistake create an empty `composer.json` file in the web folder by running `composer require drupal/some-drupal-module` from the web folder (which you often are when you run drupal console and drush commands) like this: 

```
[vagrant@local web]$ composer require drupal/devel
  [InvalidArgumentException]
  Could not find package drupal/devel at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
```

The result of this command is and empty `composer.json` file: 

```
[vagrant@local web]$ cat composer.json
{
}
```

This is of course a mistake done by me as a developer, and it has happened to me many times - and a Google search for the error messages that show up with the empty composer.json file in place is proof that I am not alone: 

```
[vagrant@local web]$ /vagrant/drupal/current/vendor/drupal/console/bin/drupal
InvalidArgumentException: The file "/vagrant/drupal/current/web/vendor/drupal/console-core//services.yml" does not exist. in /vagrant/drupal/current/vendor/symfony/config/FileLocator.php on line 44 #0 /vagrant/drupal/current/vendor/symfony/dependency-injection/Loader/YamlFileLoader.php(42): Symfony\Component\Config\FileLocator->locate('/vagrant/drupal...')
#1 /vagrant/drupal/current/vendor/drupal/console-core/src/Bootstrap/DrupalConsoleCore.php(35): Symfony\Component\DependencyInjection\Loader\YamlFileLoader->load('/vagrant/drupal...')
#2 /vagrant/drupal/current/vendor/drupal/console/src/Bootstrap/Drupal.php(101): Drupal\Console\Bootstrap\DrupalConsoleCore->boot()
#3 /vagrant/drupal/current/vendor/drupal/console/bin/drupal.php(48): Drupal\Console\Bootstrap\Drupal->boot()
#4 /vagrant/drupal/current/vendor/drupal/console/bin/drupal(4): require('/vagrant/drupal...')
#5 {main}
InvalidArgumentException: The file "/vagrant/drupal/current/web/vendor/drupal/console-core//services.yml" does not exist. in Symfony\Component\Config\FileLocator->locate() (line 44 of /vagrant/drupal/current/vendor/symfony/config/FileLocator.php).
```

Deleting the empty `composer.json` resolves this problem. 

My desired situation: That drupal console doesn't stop working even if I have an empty composer.json placed in drupal's web folder.

**Comment by webflo** [comment]
I think this is mitigated with composer 1.5.0, because it should not create a empty composer.json anymore. 

https://github.com/composer/composer/releases/tag/1.5.0
