### ISSUE TITLE
getDrupalRoot fails for Drupal 7 project 

### ISSUE THREAD

**Issue by zaporylie** [webflo/drupal-finder#19]
I did not find any information this project is limited to Drupal 8, but it fails when I try it against https://github.com/drupal-composer/drupal-project/tree/7.x. 

When I use it with D7 projects `\DrupalFinder\DrupalFinder::getDrupalRoot();` returns `/var/www/html/dr` for core located in `/var/www/html/drupal/`

This part causes problems: 
https://github.com/webflo/drupal-finder/blob/master/src/DrupalFinder.php#L110-L114

Do you have plans to add D7 support? Are you willing to accept eventual PR adding D7 support?

**Comment by hanoii** [comment]
Struggled quite a bit with this until I realized the same thing.. is D7 supposed to not use drush-shim or this?

**Comment by webflo** [comment]
I have nothing against d7 support as long we have test for it. Take a look at DrupalFinderTest

**Comment by webflo** [comment]
I never had a D7 project with site local drush :)

**Comment by webflo** [comment]
Please review https://github.com/webflo/drupal-finder/pull/22

**Comment by webflo** [comment]
Merged in https://github.com/webflo/drupal-finder/commit/99271d40466612306413c407f07f328916815b37
