### ISSUE TITLE
The latest 0.4.1 release does not work with Drush

### ISSUE THREAD

**Issue by Chi-teck** [webflo/drupal-finder#26]
I think something went wrong in [this commit](https://github.com/webflo/drupal-finder/commit/ec2a9ac737b28d5bf3f894aa59f3af4b929aab22).

https://github.com/drush-ops/drush/issues/2861

**Comment by webflo** [comment]
@Chi-teck Could you provide more info about your environment, folder names etc. Could you also try this with drush-9.0.0-beta3?

**Comment by jebschiefer** [comment]
I'm also having issues with this using drush-9.0.0-beta3 and Drupal 8.4.x-dev. My Drupal install is managed via composer if that helps.

**Comment by Chi-teck** [comment]
@webflo I confirm the issues exists in beta3. You can find information about my environment in output of `drush st` command I [posted](https://github.com/drush-ops/drush/issues/2861) in Drush issue queue. On my installation DrupalFinder::getRoot() returns path to _core_ directory.

**Comment by webflo** [comment]
@Chi-teck which project layout do you use for your Drupal site? Default or "drupal-project"-style?

**Comment by webflo** [comment]
Released Version 0.4.2 with the fix. Sorry for all the trouble. The test fixture was not correct.

**Comment by Chi-teck** [comment]
@webflo I am using default tarball from drupal.org.
