### ISSUE TITLE
Release drupal-finder 1.0.0

### ISSUE THREAD

**Issue by webflo** [webflo/drupal-finder#28]
Lets release drupal-finder 1.0.0. The lib is stable and used in various projects. This should fix the version mismatches between drush and console too.

// cc @weitzman @jmolivas

Updates needed in 
- [x] https://github.com/drush-ops/drush
- [x] https://github.com/hechoendrupal/drupal-console-core
- [x] https://github.com/drush-ops/drush-launcher
- [x] https://github.com/drupal-composer/drupal-project

**Comment by weitzman** [comment]
Sounds good to me.

**Comment by webflo** [comment]
Created a PR for drupal-console https://github.com/hechoendrupal/drupal-console-core/pull/217

**Comment by webflo** [comment]
Drush: https://github.com/drush-ops/drush/pull/2867

**Comment by webflo** [comment]
Drupal-Project: https://github.com/drupal-composer/drupal-project/pull/293

**Comment by jmolivas** [comment]
Done @webflo PR merged

**Comment by webflo** [comment]
Thx!
