### ISSUE TITLE
Drupal Finder does not find root when composer.json is not in root but in a root-subfolder

### ISSUE THREAD

**Issue by osopolar** [webflo/drupal-finder#48]
We have inherited a structure similar to:
```
/app (project root)
├── public
│   ├── drupal
|   |   ├── core
|   |   ├── autoload.php = <?php return require __DIR__ . '/../../thunder/vendor/autoload.php'; ?>
|   |   ├── index.php
|   |   └── ...
│   └── others
└── thunder
    ├── composer.json
    ├── composer.lock
    ├── sync
    └── vendor
```

This worked well using drush 8, but bootstrapping failed after upgrading to drush:

```
[bootstrap] Starting bootstrap to site [0.56 sec, 10.72 MB]
In BootstrapHook.php line 33:
  [Exception]
  Bootstrap failed. Run your command with -vvv for more information.
```

It seems that the problem lies in `DrupalFinder::isValidRoot($path)`. Hardcoding the drupal-/composer-root and vendor dir there (like below) worked:
```
$this->drupalRoot = '/app/thunder/../public/drupal';
$this->composerRoot = '/app/thunder';
$this->vendorDir = '/app/thunder/vendor';
return $this->drupalRoot && $this->composerRoot && $this->vendorDir;
```

So the problem seems to be that the assumptions on the project structure are not universal. I am not sure if this needs to be addressed in drupal-finder or in drush itself by environment variables or drush options similar to [--drupal-root](https://github.com/mglaman/drupal-check/pull/98/commits) in mglaman/drupal-check.

A workaround could be to add a (minimal) composer.json file to /app/public/drupal with following content:
```
{
    "description": "Workaround for drupal-finder to find drupal-, composer-root and vendor dir, see https://github.com/webflo/drupal-finder/issues/48",
    "extra": {
        "installer-paths": {
            "core": ["type:drupal-core"]
        }
    }
}
```

Would this be valid or may this introduce problems somewhere else?

**Comment by chris-hall-hu** [comment]
I am working on an Aquia hosted site and composer.json is one level above drupal root, as is the vendor directory. Drupal root lives in /docroot Drupal Finder is assuming is where the composer.json file is.  I believe the structure is standard for Aquia Cloud. Breaking Drupal console.

**Comment by mweimerskirch** [comment]
@osopolar
I had the same issue and worked around it by using the "COMPOSER" environment variable.
The following should work without changing your directory structure and without any code changes:

```
cd public/drupal
export COMPOSER=../../thunder/composer.json
../../thunder/vendor/bin/drush core:status (edited) 
```

**Comment by lpeabody** [comment]
What if finder checked for the presence of three environment variables, and only if all three were set would finder assign the values of the environment variables to their respective properties?

As a for-instance:

- `DRUPAL_FINDER_VENDOR=/var/www/vendor`
- `DRUPAL_FINDER_COMPOSER_ROOT=/var/www`
- `DRUPAL_FINDER_DRUPAL_ROOT=/var/www/web`

Then, add a constructor which initializes the data properties accordingly.

This would be really useful for environments that can set these variables easily, and when this information is readily known.

It's a bit OCD, maybe, but I'm building a containerized Drupal application where literally every single non-essential file is stripped out. That includes composer.json and composer.lock. Right now, if there is no composer.json file, the whole thing falls apart.

**Comment by webflo** [comment]
@lpeabody I like the idea of environment variables if the build in logic fails. It is hard to cater for everyone. Since there are a lot of non-standard setups.

**Comment by weitzman** [comment]
IMO this makes a lot of sense.

**Comment by lpeabody** [comment]
I'll have a PR up for this shortly. Writing the implementation was easy, the trick is the tests...

**Comment by lpeabody** [comment]
@weitzman @webflo I opened up a PR for this. See #55.

**Comment by goba** [comment]
Upgrade Status module also uses DrupalFinder and various people reported the issue in https://www.drupal.org/project/upgrade_status/issues/3164067, where I ended up sidetracking the problem to introduce better error handling, but its still not working well for people with composer.json locations that do not match the Drupal root expectation in DrupalFinder. See https://www.drupal.org/project/upgrade_status/issues/3194911

**Comment by lpeabody** [comment]
@webflo has been MIA since mid-December it seems. I have a PR open for this here https://github.com/webflo/drupal-finder/pull/55.
