### ISSUE TITLE
require-dev.mikey179/vfsStream is invalid, it should not contain uppercase characters. Please use mikey179/vfsstream instead.

### ISSUE THREAD

**Issue by amitsharmadoj** [webflo/drupal-finder#53]
[RuntimeException]                                                                                                             
  require-dev.mikey179/vfsStream is invalid, it should not contain uppercase characters. Please use mikey179/vfsstream instead. 

Version used:
"drupal/core": "8.8.10"
"mikey179/vfsstream": "1.6.8" 
"webflo/drupal-finder": "1.2.0"
php: 7.3.22

Today all of a sudden this error has started appearing while installing the site, can anyone update the refererence to mikey179/vfsStream in composer.json with small s rather than S

**Comment by webflo** [comment]
Fixed in https://github.com/webflo/drupal-finder/commit/1678272495a062b45bc730513e2ae76ec69f5e46 and tagged as version 1.2.1
