### ISSUE TITLE
2024-05-08 6:10 PST - Finder Error

### ISSUE THREAD

**Issue by robertfoleyjr** [webflo/drupal-finder#66]
Recently updated via composer and drush now fails.

drush status
PHP Fatal error:  Uncaught TypeError: is_link(): Argument #1 ($filename) must be of type string, Drush\Config\Environment given in /root-to-drupal/vendor/webflo/drupal-finder/src/DrupalFinder.php:153
Stack trace:
#0 /root-to-drupal/vendor/webflo/drupal-finder/src/DrupalFinder.php(153): is_link()
#1 /root-to-drupal/vendor/webflo/drupal-finder/src/DrupalFinder.php(75): DrupalFinder\DrupalFinder->discoverRoots()
#2 /root-to-drupal/vendor/drush/drush/src/Preflight/Preflight.php(310): DrupalFinder\DrupalFinder->__construct()
#3 /root-to-drupal/vendor/drush/drush/src/Runtime/Runtime.php(58): Drush\Preflight\Preflight->preflight()
#4 /root-to-drupal/vendor/drush/drush/src/Runtime/Runtime.php(40): Drush\Runtime\Runtime->doRun()
#5 /root-to-drupal/vendor/drush/drush/drush.php(139): Drush\Runtime\Runtime->run()
#6 /root-to-drupal/vendor/drush/drush/drush(4): require('...')
#7 {main}
  thrown in /root-to-drupal/vendor/webflo/drupal-finder/src/DrupalFinder.php on line 153

Fails on 
**OS:**
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"

**Php:** 8.2.18
**DB:** MariaDB version 11.2.3
**Drupal:** 10.2.6
**Drush:** 12.4.3

**Comment by webflo** [comment]
Related to https://github.com/drush-ops/drush/pull/5966 - This has been fixed in drush 12.5.2. Please make sure you use the latest version. Thanks!

**Comment by robertfoleyjr** [comment]
Confirmed, thank you.
