### ISSUE TITLE
Not working with latest acquia/lightning

### ISSUE THREAD

**Issue by jmolivas** [webflo/drupal-finder#9]
I got reported DrupalConsole is not working with `acquia/lightning` and and did tried and seems like drupal-finder is not finding the drupal site.

https://github.com/hechoendrupal/DrupalConsole/issues/2785#issuecomment-263301249

I tested by 
```
git clone git@github.com:acquia/lightning-project.git lightning
cd lightning
composer require drupal/console:~1.0
```

I also tested from my cloned repo of `drupal-finder` and dos not recognize the site

Not sure if this Installer path for drupal/core missing type  https://github.com/acquia/lightning-project/issues/23 is causing this issue.

**Comment by webflo** [comment]
Maybe we should look for drupal/core as well.

**Comment by jmolivas** [comment]
@webflo find it the `composer.json` file at the `acquia/lightning-project` does not require `drupal/core`.

The missing value is evaluated at 
https://github.com/webflo/drupal-finder/blob/master/src/DrupalFinder.php#L91

Required section at the `acquia/lightning-project`
https://github.com/acquia/lightning-project/blob/8.x/composer.json#L20-L25

The project `acquia/lightning-project` is a distribution and it does require `acquia/lightning`
https://github.com/acquia/lightning-project/blob/8.x/composer.json#L24

You can find `acquia/lightning` is the one requiring `drupal/core`
https://github.com/acquia/lightning/blob/8.x-1.x/composer.json#L115

**Comment by webflo** [comment]
Please review https://github.com/webflo/drupal-finder/pull/11

**Comment by jmolivas** [comment]
Works as expected

**Comment by webflo** [comment]
Tagged 0.2.1

**Comment by webflo** [comment]
Thx!
